version: "3.4"

services:
  db:
    image: neo4j
    ports:
      - 7474:7474 # http
      - 7687:7687 # bolt
    environment:
      - NEO4J_AUTH=neo4j/secret

  py-srv:
    build: py-srv
    healthcheck:
      test: "exit 0"
    command: sh -c "/wait && python app.py"
    environment:
      - NEO4J_AUTH=neo4j/secret
      - WAIT_HOSTS=db:7687
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    depends_on:
      - db
    links:
      - "db:db"
    ports:
      - "80:6543"
      
  py-test-srv:
    build:
      context: py-test-srv
    command: sh -c "/wait && python app.py"
    environment:
      - WAIT_HOSTS=db:7687,py-srv:6543
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    depends_on:
      - py-srv
    links:
      - "py-srv:py-srv"
